name: Run RSpec Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: test_db

        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: bundle install
    
    - name: Setup Database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Build and test with rspec
      env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
      run: bundle exec rspec